### params.yaml
# サイト: データサイエンス100本ノック＋α
k100: 
  git: 
    account: 14katsumix
    url: "https://github.com/14katsumix/100knocks-dp"
  site: 
    title: 'データサイエンス100本ノック＋α'
    edition: 
      s: '標準編' # standard
      a: '発展編' # advanced
    # rsql: '【R+SQL】'
    rsql: '[R+SQL] '
    category: 
      edition_s: 'DS-100本ノック＋α（標準編）'
      edition_a: 'DS-100本ノック＋α（発展編）'
  afiurl: 
    book: 
      amazon: "https://amzn.to/3Pmq47H"
  url: 
    book: 
      amazon: "https://amzn.to/3Pmq47H"
# 本家
k100dp: 
  title: "データサイエンス100本ノック（構造化データ加工編）"
  book: 
    title: "データサイエンス100本ノック～構造化データ加工編ガイドブック"
  git: 
    url: |
      "https://github.com/The-Japan-DataScientist-Society/100knocks-preprocess"
  # "データサイエンティスト協会"
  # "データサイエンティスト協会スキル定義委員会"

keywords: 
  - "データサイエンス100本ノック"
  - "データサイエンスブログ"
  - "データ分析"
  - "データ解析"
  - "データ分析実践"
  - "データサイエンス基礎"
  - "データサイエンスノウハウ"
  - "データサイエンスTips"
  - "データサイエンス手法"
  - "プログラミング"
  - "R言語"
  - "Rプログラミング"
  - "SQLクエリ"
  - "SQLデータベース操作"
  - "データベースバックエンド"
  - "Rデータ処理"
  - "SQLデータ処理"
  - "高度なデータ処理"
  - "データサイエンス無料教材"
  - "データサイエンス解説"
  - "データサイエンス設問解答"
  - "データサイエンス発展問題"
  - "初心者向けデータサイエンス"
  - "中級者向けデータサイエンス"
  - "上級者向けデータサイエンス"
  - "日本語データサイエンス"
  - "tidyverse"
  - "dplyr"
  - "tidyr"
  - "dbplyr"
  - "DBI"
  - "dbx"
  - "duckdb"
  - "magrittr"
  - "tibble"
  - "Data Science Blog"
  - "SQL Processing"
