baseURL: "http://localhost:1313/tech-blog/"

# permalinks を設定すると, パンクズリストがきちんと表示されなくなる.
#-> /themes/PaperMod/layouts/partials/breadcrumbs.html を修正することで解決.
#   https://github.com/adityatelange/hugo-PaperMod/issues/1585
# permalinks:
#   page:
#     # test/100k: /ds-100knocks-dp-test/:sections[1:]/:slug/
#     # test/aaa: /aaa/:year/:month/:slug/
#     # test/xxx: /xxx/:slug
#     test/xxx: /xxx/:sections[1:]/:slug
#     # xxx: /xxx/:sections[1:]/:slug
#   section:
#     # test/100k: /ds-100knocks-dp-test/:sections[1:]/
#     ## aaa: /aaa/:year/:month/
#     test/xxx: /xxx/:sections[1:]/
#     # xxx: /xxx/:sections[1:]/

params:
  # env: production # to enable google analytics, opengraph, twitter-cards and schema.
  # profile-mode
  profileMode:
    buttons:
      - name: "データサイエンス100本ノック＋α - test"
        # url: ds-100knocks-dp-test
        url: test/100k
      - name: XXX
        # url: xxx
        url: test/xxx
      - name: Archives
        url: archives
      - name: Tags
        url: tags
      - name: Github
        url: "https://github.com/14katsumix/100knocks-dp"
