baseURL: "https://14jcjc.github.io/tech-blog-2/"

# Include drafts when building.
buildDrafts: false
# buildDrafts: true

# enableRobotsTXT: true # robots.txt の生成を有効にする
enableRobotsTXT: false

services:
  googleAnalytics:
    ID: G-GLB0HGKER4
  # disqus:
  #   shortname: your-disqus-shortname
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true

# permalinks を設定すると, パンクズリストがきちんと表示されなくなる.
#-> /themes/PaperMod/layouts/partials/breadcrumbs.html を修正することで解決.
#   https://github.com/adityatelange/hugo-PaperMod/issues/1585
permalinks:
  page:
    # 100knocks: /ds-100knocks-dp/:sections[1:]/:slug/
    100knocks: /ds100knocks-alpha/:slug/
    # aaa: /aaa/:year/:month/:slug/
    # xxx: /xxx/:slug
  section:
    # 100knocks: /ds100knocks-alpha/:sections[1:]/
    100knocks: /ds100knocks-alpha/:sections[last]/
    # 100knocks: /ds100knocks-alpha/
    # aaa: /aaa/:year/:month/
    # xxx: /xxx/:sections[1:]/

mainSections: 
  - "100knocks"
  # - "test"

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  # mainSections: ["100k", "aaa", "xxx", "glossary"]

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    # enabled: true # needs to be explicitly set
    buttons:
      - name: "データサイエンス100本ノック＋α"
        # url: ds-100knocks-dp
        url: ds100knocks-alpha
      - name: "[R+SQL] 演習問題一覧"
        url: "ds100knocks-alpha/q-list"
      - name: Tags
        url: tags
      # - name: Archives
      #   url: archives

menus:
  main:
    - name: "[R+SQL] 演習問題"
      # url: "ds-100knocks-dp/common/q-list"
      url: "ds100knocks-alpha/q-list"
      weight: 10
    - name: レビュー
      # url: "categories/%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC/"
      url: "ds100knocks-alpha/book-review/"
      weight: 15
    - name: Tags
    # - name: タグ
      url: tags
      weight: 20
    - name: Archive
    # - name: アーカイブ
      url: archives
      weight: 30
    - name: Search
    # - name: 検索
      url: search
      weight: 40
    # - name: Categories
    # - name: カテゴリー
      # url: categories
      # weight: 50
    # - name: "データサイエンス100本ノック＋α"
    #   url: ds-100knocks-dp
    #   weight: 60
    #   identifier: "DS-100knocks"
    # - name: standard
    #   url: "ds-100knocks-dp/standard"
    #   parent: "DS-100knocks"
    #   weight: 1
    #   identifier: standard
    # - name: advanced
    #   url: "ds-100knocks-dp/advanced"
    #   parent: "DS-100knocks"
    #   weight: 2
    #   identifier: advanced
    # - name: Glossary
    #   url: glossary
    #   weight: 30

module:
  mounts:
  - excludeFiles: 
      - test/books/**
      # - docs/**
    source: content
    target: content
  - source: static
    target: static
  - source: layouts
    target: layouts
  - source: data
    target: data
  - source: assets
    target: assets
  - source: i18n
    target: i18n
  - source: archetypes
    target: archetypes
